### ISSUE TITLE
Test out using Discord for meetings/co-working and the reasons why

### ISSUE THREAD

**Issue by lwjohnst86** [science-collective/admin#4]
I've been giving this some thought and I think we should test out using [Discord](https://discord.com/) for communication and meetings, specifically for this project and doing co-working sessions. These are the reasons why I think it might be better than the alternatives of using Slack + Zoom:

1. Discord combines audio conferencing and chat messaging, while we'd have to use two apps (Slack and Zoom) for the same purposes.
2. For an open community, Discord is easier to find and join compared to Slack and Zoom.
3. Specifically for co-working sessions, having a Zoom meeting open for hours on end is a) not environmentally sustainable, b) excessive for our purposes, and c) not how co-working works, since people will jump in and out of the conversation, which isn't easy to do with Zoom. Discord was designed around being able to easily jump in and out of a call... it was designed for friends playing video games together but now many large online communities use it for things other than video games. Discord I think by default does audio first and it does it really well. For co-working we don't need video, realistically.

A down side to using Discord is that it is another app to learn and use, but practically, if you've used Slack there aren't too many differences. And we can have contributing docs to help learn to use it. 

Thoughts?

**Comment by Aastedet** [comment]
Never used Discord before, but I see it being used in online communities everywhere, so I suppose it can't be too bad, and it definitely makes sense to adopt.
It's a yay! from me.

**Comment by danielibsen** [comment]
I also think it would be worth giving it a try given your arguments above.

**Comment by MarioGuCBMR** [comment]
I have used discord a couple of times and, in the end, becomes way more comfortable to work with! I think we should go for it!

**Comment by Aastedet** [comment]
Turns out Zoom closed the meeting after 40 minutes of idle today, so unless we keep really chatty, Zoom is no good.

**Comment by lwjohnst86** [comment]
Ok, it's decided, we'll test out using Discord for next session #7
